---
- hosts: 127.0.0.1
  connection: local
  name: Delete an User
  gather_facts: false

  tasks:

    - name: Delete an User
      become: yes
      user:
        name: "{{ username }}"
        state: absent
        remove: true
      register: result
    - debug: var=result

