---
- hosts: 127.0.0.1
  connection: local
  name: Initialize Git config
  gather_facts: false

  tasks:

    - name: Disable verifying SSL
      git_config:
        name: http.sslVerify
        scope: global
        value: false

    - name: Enable credential store
      git_config:
        name: credential.helper
        scope: global
        value: store

    - name: Pull only for fast forward
      git_config:
        name: pull.ff
        scope: global
        value: only
