---
- hosts: 127.0.0.1
  connection: local
  name: Initialize Git config
  gather_facts: false
  become: yes
  become_user: "{{ username }}"

  tasks:

    - name: Disable verifying SSL
      git_config:
        name: http.sslVerify
        scope: global
        value: false

    - name: Enable credential store
      git_config:
        name: credential.helper
        scope: global
        value: store

    - name: Pull only for fast forward
      git_config:
        name: pull.ff
        scope: global
        value: only

    - name: Configure git-delta
      git_config:
        name: core.pager
        scope: global
        value: delta

    - name: Configure git-delta
      git_config:
        name: interactive.diffFilter
        scope: global
        value: delta --color-only

    - name: Configure git-delta
      git_config:
        name: delta.navigate
        scope: global
        value: true

    - name: Configure git-delta
      git_config:
        name: delta.side-by-side
        scope: global
        value: true

    - name: Configure git-delta
      git_config:
        name: merge.conflictstyle
        scope: global
        value: diff3
