---
- hosts: 127.0.0.1
  connection: local
  name: Install dotfiles
  gather_facts: false

  tasks:

    - name: Install configurations of zsh, tmux, tig, and fzf
      become: yes
      become_user: "{{ username }}"
      shell: cd ~ && curl -L https://raw.github.com/nimo1491/rc/master/auto-install.sh | bash

    - name: Install vimrc
      become: yes
      become_user: "{{ username }}"
      shell: cd ~ && curl -L https://raw.github.com/nimo1491/vimrc/master/auto-install.sh | bash -s nvim


