---
- hosts: 127.0.0.1
  connection: local
  name: Install packages
  gather_facts: false
  become: yes

  tasks:

    # - name: Add repository for Vim 8.1+
    #   apt_repository:
    #     repo: ppa:jonathonf/vim

    - name: Add repository for ripgrep
      apt_repository:
        repo: ppa:x4121/ripgrep

    - name: Add repository for nvim
      apt_repository:
        repo: ppa:neovim-ppa/stable

    - name: Perform "apt-get update"
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        pkg:
        - curl
        - zsh
        - git
        - tig
        - tmux
        - fasd
        - ctags
        - neovim
        - ripgrep
        - ipmitool
        - clang-format
        - clangd-10

    - name: Create soft link for clangd
      file:
        src: /usr/bin/clangd-10
        dest: /usr/bin/clangd
        state: link
        force: yes

    - name: Install bat
      apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.18.3/bat_0.18.3_amd64.deb

    - name: Install required packages for Docker
      apt:
        pkg:
        - ca-certificates
        - gnupg
        - lsb-release

    - name: Add Dockers' official GPG key
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        warn: false

    - name: Set up Dockers' stable repository
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        warn: false

    - name: Perform "apt-get update"
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add Node.js LTS repository
      shell: >
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      args:
        warn: false

    - name: Install Node.js
      apt:
        pkg:
        - nodejs
        state: latest

    - name: Add yarn repository
      shell: >
        curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg |
        gpg --yes --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
        echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" |
        sudo tee /etc/apt/sources.list.d/yarn.list
      args:
        warn: false

    - name: Perform "apt-get update"
      apt:
        update_cache: yes

    - name: Install yarn
      apt:
        pkg:
        - yarn
        state: latest
