---
- hosts: 127.0.0.1
  connection: local
  name: Install packages
  gather_facts: false
  become: yes

  tasks:

    # - name: Add repository for Vim 8.1+
    #   apt_repository:
    #     repo: ppa:jonathonf/vim

    - name: Add repository for ripgrep
      apt_repository:
        repo: ppa:x4121/ripgrep

    - name: Add repository for nvim
      apt_repository:
        repo: ppa:neovim-ppa/stable

    - name: Add clang-format official GPG key
      shell: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      args:
        warn: false

    - name: Add clang-format binary repository
      apt_repository:
        repo: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
        state: present

    - name: Add clang-format source repository
      apt_repository:
        repo: deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
        state: present

    - name: Perform "apt-get update"
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        pkg:
        - curl
        - zsh
        - git
        - git-lfs
        - tig
        - tmux
        - fasd
        - ctags
        - neovim
        - ripgrep
        - coreutils
        - ipmitool
        - clangd-10
        - python3-venv
        - python3-pip

    - name: Install clang-format
      apt:
        pkg:
        - clang-format-10

    - name: Create soft link for clangd
      file:
        src: /usr/bin/clangd-10
        dest: /usr/bin/clangd
        state: link
        force: yes

    - name: Create soft link for clang-format
      file:
        src: /usr/bin/clang-format-10
        dest: /usr/bin/clang-format
        state: link
        force: yes

    - name: Install bat
      apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.18.3/bat_0.18.3_amd64.deb

    - name: Install required packages for Docker
      apt:
        pkg:
        - ca-certificates
        - gnupg
        - lsb-release

    - name: Add Dockers' official GPG key
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        warn: false

    - name: Set up Dockers' stable repository
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        warn: false

    - name: Perform "apt-get update"
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add Node.js LTS repository
      shell: >
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      args:
        warn: false

    - name: Install Node.js
      apt:
        pkg:
        - nodejs
        state: latest

    - name: Add Node.js LTS repository
      shell: >
        npm install --global --force yarn
