---
- hosts: 127.0.0.1
  connection: local
  name: Setup prerequisite environment
  gather_facts: false
  become: yes

  tasks:

    - name: Create "developer" group
      become: yes
      group:
        name: developer
        state: present

    - name: Create workspace root
      become: yes
      file:
        path: "{{ workspace_root }}"
        state: directory
        group: developer
        mode: '0775'
