---
- hosts: 127.0.0.1
  connection: local
  name: Install packages
  gather_facts: false
  become: yes

  tasks:

    - name: Ensure group "developer" exists
      become: yes
      group:
        name: developer
        state: present

    - name: Perform "apt-get update"
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        pkg:
        - schroot

    - name: Update configurations
      blockinfile:
        path: /etc/schroot/schroot.conf
        backup: yes
        insertafter: EOF
        block: |
          [v13]
          description=Ubuntu 18.04
          type=directory
          directory=/src/chroot/v13
          shell=/bin/bash
          root-groups=developer
          preserve-environment=true
